### DISCUSSION TITLE
Convert Definition Lists (`<dl>`) to Frames (`<fieldset>`) | /en/2023/11/dl-fieldset/

### DISCUSSION THREAD

**Discussion by giscus** [rbind/yihui#1536] [Comments]
When I suggested a department chair in 2019 that they may consider opening a blog so that all students and faculty in the department can write together (which sounded exciting to me), he expressed a &hellip;

https://yihui.org/en/2023/11/dl-fieldset/

**Comment by chuxinyuan** [comment]
谢谢，刚给我的博客加上这项新功能。不过我的背景色用的 "#E5EAEF"，整体上颜色更接近莫兰迪色系。

**Comment by chuxinyuan** [comment]
```css
dl, fieldset {
  background-color: lightyellow;
  font-size: .9em;
  border-width: 1px;
}
```

这里我设置背景色为 "#E5EAEF" 后在火狐浏览器里边框不显示，我显式地加入了 border: 1px solid #ddd;后显示效果和谷歌浏览器一样了。难道是火狐浏览器采用的是覆盖，而谷歌浏览器则是合并？
