### DISCUSSION TITLE
TODO / 待办事项 | /todo/

### DISCUSSION THREAD

**Discussion by yihui** [rbind/yihui#282] [Comments]
https://yihui.org/todo/

**Comment by earfanfan** [comment]
哇，好多事项啊。不过我一个都帮不上忙，只是正好溜达着路过~

原来休假并不是停下来，把脑袋清空，然后静静感受时间流逝啊~

**Comment by yihui** [comment]
两段话同样的字符数，真整齐啊，读起来就像读诗。

休假只是把工作扔掉，大力更博，写起来名正言顺。

更博正是把脑袋清空，堵车严重，疏通完才能静静。

文字总是召唤强迫症，又没时间，休假专心发神经。

> 不过我一个都帮不上忙

好了，说人话。如果你真想帮忙的话，我也可以列举一些简单的任务的。

**Comment by earfanfan** [comment]
>两段话同样的字符数

这竟然也能被注意到啊。我确实是打完字发现两段话一样长，就顺手加了两个波浪号。

如果真得有简单的任务的话，不妨列几个。不过不用迁就我这小白水平而硬想一些简单的任务。

**Comment by yihui** [comment]
好的，放心，不会迁就，我通常不是个迁就人的人。

**Comment by XiangyunHuang** [comment]
> **TODO**
>
> 17. A possible book: Presentation Ninja (xaringan, ioslides, slidy, revealjs, PowerPoint, beamer, shower, etc).

我可能帮得上点忙，网页技术是我准备学习的一个方向。

**Comment by yihui** [comment]
@XiangyunHuang 这个其实不太需要多少技术学习，主要是想着写本书，介绍所有的基于 R Markdown 制作幻灯片的工具。

**Comment by yihui** [comment]
@earfanfan 因为你前段时间提到了递归，今天我刚好在想一个递归问题，你看要不要试试。事情是这样：在 blogdown 包中我有个 `blogdown::write_toml` 函数讲 R 对象转换为 TOML 格式，这里面用的是假道伐虢的黑魔法（先转 YAML 再用 Hugo 转 TOML），但我觉得这事应该是可以用原生 R 代码直接大致实现的。我有个类似的函数 `xfun::tojson` 在这里：https://github.com/yihui/xfun/blob/main/R/json.R 原理很像，就是往列表里层层递归。TOML 语法在此：https://toml.io

目标是将如此这般的列表

```r
list(
  build = list(
    command = 'hugo',
    publish = 'public',
    environment = list(HUGO_VERSION = '0.89.2')
  ),
  context = list(
    production = list(
      environment = list(HUGO_ENV = "production")
    ),
    `deploy-preview` = list(
      command = "hugo -F -b $DEPLOY_PRIME_URL"
    )
  )
)
```

转化为

```toml
[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.89.2'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
```

这事应该不算难，就是进入盗梦空间有点累脑阔。
